title: Aurélien Duboc
description: "Aurélien Duboc"
author:
  name: "Aurélien Duboc"
  email: "aurelien@duboc.xyz"
  url: "https://www.duboc.xyz"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  writeups: 
    output: true
  awards:
    output: false

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Aurélien Duboc"
year : "2019"
